api:
  prefix: /api
cellphone: {}
database:
  adapter: sqlite
  db_name:
  host: localhost
  password:
  port: 5432
  user:
  echo: false
  db_core: true
  path:
flask:
  debug: false
  sqlalchemy_track_modifications: false
  secret_key: 5e7ca92615435457f491e6546ee4b092a6497a47d894bb21
app:
  debug: false
  threads: 4
  verbose: true